### ISSUE TITLE
Nejde mi změnit ikona 

### ISSUE THREAD

**Issue by Xplej** [NightlightOfficial/Nightlight#2]
Dobrý den, v NightLightu mi nejde změnit ikona a background už čekám 34 minut a nic se nestalo. Dopředu děkuji. Plej

**Comment by iTenerai** [comment]
Dobrý den, Vaše ikona nyní vypadá takhle.

![image](https://user-images.githubusercontent.com/106991725/208503791-07b2d07f-3e2a-4141-bb98-662d000e6e53.png)

Využíváte současně Nightlight na mobilním zařízení, nebo na počítači?

**Comment by Xplej** [comment]
Dobrý den, používám jenom mobilní telefon a  nevíte proč se mě to
nezobrazuje?

pondělí 19. prosince 2022 iTenerai ***@***.***> napsal(a):

**Comment by iTenerai** [comment]
Jde nejspíše o chybu prohlížeče. Prohlížeče uchovávají po nějakou dobu obrázky ze stránek v interní paměti, proto se Vám ukazuje stále stejný obrázek. Pokud chcete ikonu vydět okamžitě, doporučuji v nastavení prohlížeče vymazat cache.
