### ISSUE TITLE
Follow list not showing

### ISSUE THREAD

**Issue by AdamantConlanger** [NightlightOfficial/Nightlight#3]
When clicking on "followers" or "following", a popup screen appears. It does say "loading" for a second or two, but it doesn't display the followers/followed users after that. This happens on multiple users' accounts and in both Brave and Firefox. In private windows, the popup doesn't open at all (though the cursor still becomes a grabby hand).

![image](https://github.com/NightlightOfficial/Nightlight/assets/79029774/8c378fc7-fece-4826-b66b-4d73ec6a0e94)

**Comment by iTenerai** [comment]
Thank you for reporting this issue. Do you happen to have JavaScript disabled?

**Comment by iTenerai** [comment]
I am not able to replicate this issue, I can recommend doing the following:

1. Check if likes list on posts works
2. Check your internet connection speed
3. Make sure you are logged in, viewing follower and following list is only available once logged in
4. Try refreshing the page or wait a bit

**Comment by AdamantConlanger** [comment]
Like lists work. But once I try to view a follow list, they stop working (though the grabby hand still appears). I've checked my browser settings, and js is enabled. Even when turning off Brave's Shields and Firefox's Enhanced Tracking Protection and disabling pop-up blocking, follow lists don't work.

**Comment by AdamantConlanger** [comment]
oh, in addition to not being able to view like lists after trying to view a follow list, it's also impossible to like posts.

**Comment by iTenerai** [comment]
After a day I am still unable to replicate this issue, I will continue to keep focus on it, but for now there's not much I can do without more info.

**Comment by AdamantConlanger** [comment]
I've checked the console, and it narrows down the problem considerably:
![image](https://github.com/NightlightOfficial/Nightlight/assets/79029774/8677a8ca-53f0-4567-a1cf-3633d3b01ede)

I've noticed that the follow lists are parsed using `likesArray = JSON.parse(this.responseText)['followers'];`, while like lists are parsed using `likesArray = this.responseText.split(";");`. There's probably something going on there. Also, follow lists don't have the line `if (isBusy) return;` at the start of their event listener, while like lists do. I'm no web dev, so I'm just guessing. But I hope that this does help.

**Comment by AdamantConlanger** [comment]
And seen as `createLikesList` errors, the event listener doesn't execute the code that's supposed to run after setting up the follow list. This skipped code probably includes some aspect of displaying the list, as well as setting `isBusy` to false again. The latter causes the event listeners for like lists to return immediately, which is why I couldn't open like lists after trying to open a follow list. It might be a good idea to add some fail-safe measures that run when certain exceptions are caught.

**Comment by iTenerai** [comment]
> I've checked the console, and it narrows down the problem considerably: ![Screenshot 2023-09-09 213350 (1)](https://user-images.githubusercontent.com/79029774/266799682-40dc1996-f0dc-43bb-b748-0ec5c85a2a4c.png)
> 
> I've noticed that the follow lists are parsed using `likesArray = JSON.parse(this.responseText)['followers'];`, while like lists are parsed using `likesArray = this.responseText.split(";");`. There's probably something going on there. Also, follow lists don't have the line `if (isBusy) return;` at the start of their event listener, while like lists do. I'm no web dev, so I'm just guessing. But I hope that this does help.

Thanks for the valuable info, I will try to figure out why this problem occurs. So far no other user had a similar problem, so it is difficult to track down this issue.

**Comment by iTenerai** [comment]
The issue should now be fixed, please try it again and let me know if it works for you.

**Comment by AdamantConlanger** [comment]
I can confirm that it works now. Thanks!
