### ISSUE TITLE
store page not loading when not logged in

### ISSUE THREAD

**Issue by AdamantConlanger** [NightlightOfficial/Nightlight#4]
When not logged in, the store webpage (https://night-light.cz/store) never stops displaying the loading animation. This happens in both Brave and Firefox and both in private and regular windows. Logging in fixes the issue.

![image](https://github.com/NightlightOfficial/Nightlight/assets/79029774/0e0daec8-3a8e-4073-bfce-c0d8e1de1767)

**Comment by iTenerai** [comment]
This issue was fixed, thank you for reporting it.
